image: gcc

build:
  stage: build

  before_script: 
    - apt update && apt -y install make autoconf automake libtool libboost-dev libboost-system-dev
  script: 
    - ./autogen.sh --disable-spreadsheet-model && make

test:
  stage: test
  script:
    - make check
